### PR TITLE
fixed Background Image Issue

### PR DESCRIPTION
**Pull request by JayantGoel001**
Previously
image

Now
image

### CODE REVIEW

**Review by AvidCoder101 — APPROVED** [review]
Thanks for your contribution and your styling work @JayantGoel001 🙂. Great work! LGTM, @CodingSpecies, what do you think?

**Comment by AvidCoder101** [comment]
@all-contributors please add @JayantGoel001 for content, design

**Comment by AvidCoder101** [comment]
@all-contributors please add @AvidCoder101 for projectManagement, code, doc, review

**Review by NS007-dev — APPROVED** [review]
This is so much more user-friendly! Thank you for your contribution @JayantGoel001 .

**Comment by AvidCoder101** [comment]
@all-contributors please add @CodingSpecies for review

**Pull request merged**
